name: Build and Push Docker Image

on:
  push:
    branches:
      - '**' # Trigger this workflow on push to the main branch (you can adjust as needed)

jobs:
  job1:
    uses: ./.github/workflows/tests-e2e.yml # Running the end-to-end tests workflow

  job2:
    uses: ./.github/workflows/tests-unit.yml # Running the unit tests workflow

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2] # Ensure job3 runs only after both job1 and job2 complete successfully

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Ensure we have the latest repository state

      # Log in to Docker Hub using your secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t shahdm96/nuxtmoviesdb:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Docker Push
        run: docker push shahdm96/nuxtmoviesdb:${{ github.sha }}
