name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      # Log in to Docker Hub securely using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Image
        run: docker build -t shahdm96/nuxtmoviesdb:${{ github.sha }} .

      - name: Docker Push
        run:  docker push shahdm96/nuxtmoviesdb:${{ github.sha }}

