name: Tests e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      app:
        image: your-app-image:latest
        ports:
          - 3000:3000 # Adjust based on your app's port
        options: --health-cmd="curl --fail http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Start Playwright Test Container
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/app \
            -w /app \
            mcr.microsoft.com/playwright:v1.42.0 \
            /bin/bash -c "pnpm install && npx playwright install --with-deps && npx playwright test"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
